WIDTH = 600
HEIGHT = 600
WIDTH_HALF = WIDTH // 2
HEIGHT_HALF = HEIGHT // 2

MOVE_DISTANCE = 20
UP = 90
DOWN = 270
LEFT = 180
RIGHT = 0

STARTING_POSITIONS = [(0, 0), (-MOVE_DISTANCE, 0), (-MOVE_DISTANCE * 2, 0)]

ALIGNMENT = "center"
FONT = ("Courier", 24, "normal")
